# This is where you can edit round settings
round:
  # This is Used for Block Breaking Protection
  breakable_blocks:
    - OAK_PLANKS
  secondsPerRound: 60

# This is where you can change spawn settings
spawn:
  # This is Used to Protect Spawn-ables(Players and Chests) from spawning in specific blocks
  unspawnable_Blocks:
    - LAVA
    - WATER

# This is where you can add imported worlds as Lobbies
lobby_worlds:
  world:
    spawn:
      mapCoords:
        xMin: -100
        xMax: 100
        zMin: -100
        zMax: 100
    chests:
      max_chests: 4
    border:
      max_border_size: 500

# This is Used for the Lobby Selector
gui_items:
  lobby_hand_item:
    display_name: '&6Lobbies'
    slot: 8
    material: BOOKSHELF
    lore:
      - '&2Find out More'
  custom_items:
    Lobby_1:
      display_name: '&bLobby 1'
      world: world
      slot: 10
      material: BOOKSHELF
      lore:
        - '&1What?'

# This is Plugin Hooking Management
plugins:
  placeholderAPI:
    usePlaceholderAPI: true
  vault:
    useVault: true
